### PR TITLE
Switch to new compilers and add run_exports

### PR DESCRIPTION
**Pull request by mariusvniekerk**

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@conda-forge-admin , please rerender

**Comment by mariusvniekerk** [comment]
@conda-forge-admin , please rerender

**Review by xhochy — APPROVED** [review]
Nice, is there some news item on conda-forge now supporting the new compilers?

**Comment by mariusvniekerk** [comment]
@conda-forge-admin , please rerender

**Comment by mariusvniekerk** [comment]
@xhochy We are in the process of doing the move.  I'm making all my new things using it now

**Pull request merged**
